# Generated by Django 3.0 on 2024-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=30)),
            ],
        ),
    ]
